services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: technical-support-backend
    env_file:
      - .env
    depends_on:
      postgres:
        condition: service_started
    restart: unless-stopped
    networks:
      - app_network
      - traefik-public
    labels:
      - traefik.enable=true
      - traefik.docker.network=traefik-public
      - traefik.http.routers.tech-support.rule=Host(`${DOMAIN}`) && PathPrefix(`/support-back`)
      - traefik.http.routers.tech-support.entrypoints=web
      - traefik.http.routers.tech-support.middlewares=tech-support-strip
      - traefik.http.routers.tech-support-secure.rule=Host(`${DOMAIN}`) && PathPrefix(`/support-back`)
      - traefik.http.routers.tech-support-secure.entrypoints=websecure
      - traefik.http.routers.tech-support-secure.tls=true
      - traefik.http.routers.tech-support-secure.tls.certresolver=letsencrypt
      - traefik.http.routers.tech-support-secure.middlewares=tech-support-strip
      - traefik.http.middlewares.tech-support-strip.stripprefix.prefixes=/support-back
      - traefik.http.services.tech-support.loadbalancer.server.port=8123

  postgres:
    image: postgres:16
    env_file:
      - .env
    volumes:
      - postgres_data:/var/lib/postgresql/data
    restart: unless-stopped
    networks:
      - app_network

volumes:
  postgres_data:

networks:
  app_network:
    driver: bridge
  traefik-public:
    external: true
    name: traefik-public