"""remove head_user_id column from departments table

Revision ID: 8bec89f7f686
Revises: 667483476a36
Create Date: 2026-04-07 20:00:01.629515

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8bec89f7f686'
down_revision: Union[str, Sequence[str], None] = '667483476a36'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('departments_head_user_id_fkey'), 'departments', type_='foreignkey')
    op.drop_column('departments', 'head_user_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('departments', sa.Column('head_user_id', sa.UUID(), autoincrement=False, nullable=False))
    op.create_foreign_key(op.f('departments_head_user_id_fkey'), 'departments', 'users', ['head_user_id'], ['id'])
    # ### end Alembic commands ###
