"""fix worker_id nullable

Revision ID: fix_worker_id_nullable
Revises: 8bec89f7f686
Create Date: 2026-08-20 20:00:00.000000

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'fix_worker_id_nullable'
down_revision: Union[str, Sequence[str], None] = '8bec89f7f686'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('orders', 'worker_id',
               existing_type=postgresql.UUID(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('orders', 'worker_id',
               existing_type=postgresql.UUID(),
               nullable=False)
    # ### end Alembic commands ###