"""add subrole in users table

Revision ID: 667483476a36
Revises: 2efedb440c94
Create Date: 2026-04-07 19:55:27.669982

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '667483476a36'
down_revision: Union[str, Sequence[str], None] = '2efedb440c94'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('orders', sa.Column('worker_id', sa.UUID(), nullable=False))
    op.alter_column('orders', 'description',
               existing_type=sa.TEXT(),
               type_=sa.String(length=511),
               existing_nullable=False)
    op.drop_constraint(op.f('orders_worker_fkey'), 'orders', type_='foreignkey')
    op.create_foreign_key(None, 'orders', 'users', ['worker_id'], ['id'])
    op.drop_column('orders', 'worker')
    op.add_column('users', sa.Column('subrole', sa.Enum('SUPER_ADMIN', 'ADMIN', 'USER', name='role'), nullable=False))
    op.add_column('users', sa.Column('head_of_department_id', sa.UUID(), nullable=True))
    op.create_foreign_key(None, 'users', 'departments', ['head_of_department_id'], ['id'])
    op.drop_column('users', 'role')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('role', postgresql.ENUM('SUPER_ADMIN', 'ADMIN', 'USER', name='role'), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'users', type_='foreignkey')
    op.drop_column('users', 'head_of_department_id')
    op.drop_column('users', 'subrole')
    op.add_column('orders', sa.Column('worker', sa.UUID(), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'orders', type_='foreignkey')
    op.create_foreign_key(op.f('orders_worker_fkey'), 'orders', 'users', ['worker'], ['id'])
    op.alter_column('orders', 'description',
               existing_type=sa.String(length=511),
               type_=sa.TEXT(),
               existing_nullable=False)
    op.drop_column('orders', 'worker_id')
    # ### end Alembic commands ###
